development:
  adapter: mysql2
  database: my_interview_development
  host: 127.0.0.1
  username: root
  password:
  pool: 5

production:
  adapter: mysql2
  database: my_interview_development
  host: 127.0.0.1
  username: root
  password:
  pool: 5
